FROM rabbitmq:3.13.0-management

# RUN rabbitmqctl add_user admin pwd
# RUN rabbitmqctl set_user_tags admin administrator
# RUN rabbitmqctl-plugins enable rabbitmq_management

EXPOSE 15672
EXPOSE 5672

CMD ["rabbitmq-server"]