# This workflow will run tests for the front-end portion of the nodejs-starter

name: front-end/dev

on:
  push:
    branches:
      - front-end/dev*
  pull_request:
    branches:
      - front-end/dev*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.x

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Dependencies
        run: npm --prefix Source/ReactFrontEnd install

      - name: Build Docker Image
        run: | 
          docker build -f Source/ReactFrontEnd/Dockerfile -t nodejs-starter:ReactFrontEnd Source/ReactFrontEnd

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 8443:8443 --name ReactFrontEnd nodejs-starter:ReactFrontEnd
          sleep 15

      - name: Test Health Endpoint
        run: | 
          curl --fail http://localhost:8080/health || exit 1

      - name: Clean-up Docker Container
        run: |
          docker stop ReactFrontEnd
          docker rm ReactFrontEnd

      - name: Run tests
        run: npm --prefix Source/ReactFrontEnd test
        env:
          CI: true
