# This workflow will run tests for the front-end portion of the nodejs-starter

name: front-end/dev

on:
  push:
    branches:
      - front-end/dev*
  pull_request:
    branches:
      - front-end/dev*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.x

      - name: Install Dependencies
        run: npm --prefix Source/ReactFrontEnd install

      - name: Run tests
        run: npm --prefix Source/ReactFrontEnd test
        env:
          CI: true
