# This workflow will run tests for the front-end portion of the nodejs-starter

name: front-end/dev

on:
  push:
    branches:
      - front-end/dev*
  pull_request:
    branches:
      - front-end/dev*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.x

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_RESOURCE_REGION }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Dependencies
        run: npm --prefix Source/ReactFrontEnd install

      - name: Build Docker Image
        run: | 
          docker build -f Source/ReactFrontEnd/Dockerfile -t nodejs-starter:ReactFrontEnd Source/ReactFrontEnd

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 -p 8443:8443 --name ReactFrontEnd nodejs-starter:ReactFrontEnd
          sleep 15

      - name: Test Health Endpoint
        run: | 
          curl --fail http://localhost:8080/health || exit 1
          curl http://localhost:8080/health

      - name: Clean-up Docker Container
        run: |
          docker stop ReactFrontEnd
          docker rm ReactFrontEnd

      - name: Run tests
        run: npm --prefix Source/ReactFrontEnd test
        env:
          CI: true

      # Log in to the AWS ECR service
      - name: Log in to ECR
        run: aws ecr get-login-password --region ${{ vars.AWS_RESOURCE_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{ vars.AWS_RESOURCE_REGION}}.amazonaws.com

      - name: Re-tag Docker Image
        run: docker tag nodejs-starter:ReactFrontEnd ${{ vars.ECR_URI }}:nodejs-starter-reactfrontend

      - name: Push Image to ECR
        run: docker push ${{ vars.ECR_URI }}:nodejs-starter-reactfrontend
